### ISSUE TITLE
how to use this adaptive softmax to calculate sentence probability.?

### ISSUE THREAD

**Issue by OswaldoBornemann** [TencentAILab/tf-adaptive-softmax-lstm-lm#6]
It seems that the code just calculate specific word loss. So how to implement it to calculate the whole sentence probability?

**Comment by yangsaiyong** [comment]
The sentence log-probabily is the sum of log-probability of each word in the sentence, including the end-of-sentence word "</s>".

**Comment by yangsaiyong** [comment]
> It seems that the code just calculate specific word loss. So how to implement it to calculate the whole sentence probability?

The sentence log-probabily is the sum of log-probability of each word in the sentence, including the end-of-sentence word "".
